apiVersion: v1
kind: Secret
metadata:
  name: {{ include "accessbot.fullname" . }}
  labels:
    {{- include "accessbot.labels" . | nindent 4 }}
type: Opaque
stringData:
  SDM_API_ACCESS_KEY: "{{ .Values.strongdm.api_access_key }}"
  SDM_API_SECRET_KEY: "{{ .Values.strongdm.api_secret_key }}"
  {{- if .Values.slack.enabled }}
  SDM_BOT_PLATFORM: "slack"
  SLACK_APP_TOKEN: "{{ .Values.slack.app_token }}"
  SLACK_BOT_TOKEN: "{{ .Values.slack.bot_token }}"
  {{- end}}
  {{- if .Values.teams.enabled }}
  SDM_BOT_PLATFORM: "ms-teams"
  AZURE_APP_ID: "{{ .Values.teams.app_id }}"
  AZURE_APP_PASSWORD: "{{ .Values.teams.app_password }}"
  {{- end }}
