scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "accessbot_metrics"
    scrape_interval: 5s
    static_configs:
      - targets: ["accessbot:3142"]
