from enum import Enum


class MetricGaugeType(Enum):
    TOTAL_RECEIVED_MESSAGES = "TOTAL_RECEIVED_MESSAGES"
    TOTAL_ACCESS_REQUESTS = "TOTAL_ACCESS_REQUESTS"
    TOTAL_MANUAL_APPROVES = "TOTAL_MANUAL_APPROVES"
    TOTAL_AUTO_APPROVES = "TOTAL_AUTO_APPROVES"
    TOTAL_MANUAL_DENIES = "TOTAL_MANUAL_DENIES"
    TOTAL_TIMED_OUT_REQUESTS = "TOTAL_TIMED_OUT_REQUESTS"
    TOTAL_PENDING_REQUESTS = "TOTAL_PENDING_REQUESTS"
    TOTAL_CONSECUTIVE_ERRORS = "TOTAL_CONSECUTIVE_ERRORS"
